.github/workflows/ci.yml, libs/agent/.babelrc, libs/agent/.eslintrc.json, libs/agent/README.md, libs/agent/jest.config.ts, libs/agent/package.json, libs/agent/project.json, libs/agent/release.config.js, libs/agent/src/index.ts, libs/agent/src/lib/agent.spec.ts, libs/agent/src/lib/agent.ts, libs/agent/tsconfig.json, libs/agent/tsconfig.lib.json, libs/agent/tsconfig.spec.json, package.json, release.config.base.js, tsconfig.base.json, yarn.lock
this is just a stub library generated by nx, the purpose of this commit is to get package publishing working with semantic-release
=> feat(agent): initialise agent library

packages/cli/default/default.yml
fixes https://github.com/uncefact/project-vckit/issues/80
=> fix: add correct api-doc router to default config

packages/cli/default/default.yml, packages/cli/src/createCommand.ts, packages/cli/src/credentialOA.ts, packages/core-types/package.json, packages/core-types/src/plugin.schema.json, packages/credential-oa/src/action-handler.ts, packages/credential-oa/src/index.ts, packages/remote-client/src/openApi.ts, packages/remote-server/src/agent-router.ts
This PR refactors the credential OA for document schema and adds a cli for demo.
- The API `POST /credentials/issue` will point to the handler of credential OA.
- The cli for credential OA: 
```
pnpm vckit credentialOA
```
=> refactor: credential OA

packages/e2e/README.md, packages/e2e/__tests__/credentialW3c.ts, packages/e2e/integration-tests/browserAgent.e2e.ts, packages/e2e/integration-tests/restAgent.e2e.ts, packages/e2e/jest.config.cjs, packages/e2e/package.json, packages/e2e/src/vckit/setup.ts, packages/e2e/tsconfig.json
This pull request introduces an end-to-end (e2e) testing package to enhance the testing capabilities of vckit. The e2e testing package allows us to test compatibility of vckit packages.
https://github.com/uncefact/project-vckit/issues/84
=> test: add the e2e testing package

packages/credential-oa/src/action-handler.ts
- Get the correct information for OA issuer
=> fix: get correct information for issuer for OA document

packages/cli/package.json, packages/vc-api/README.md, packages/vc-api/src/config/index.ts, packages/vc-api/src/index.ts, packages/vc-api/src/issuer-router.ts, packages/vc-api/src/middlewares/index.ts, packages/vc-api/src/middlewares/issuer.ts, packages/vc-api/src/middlewares/verifier.ts, packages/vc-api/src/types/issuer.ts, packages/vc-api/src/types/verifier.ts, packages/vc-api/src/utils/mapping.ts, packages/vc-api/src/verifier-router.ts, pnpm-lock.yaml
=> feat: implement vc api verifier router

packages/credential-oa/src/action-handler.ts
Custom the verifier for credential OA to verify the `openAttestationDidIdentityProof`
=> fix: add did identity proof check for oa verify

packages/credential-oa/src/action-handler.ts
verifier page shows credential details when valid, so valid credential needs to be returned in response from agent
=> feat: include credential in response from agent

packages/cli/package.json, packages/core-types/package.json, packages/core-types/src/index.ts, packages/core-types/src/plugin.schema.json, packages/core-types/src/types/IRevocationList2020.ts, packages/encrypted-storage/src/encrypted-storage.ts, packages/encrypted-storage/src/identifier/encrypted-data-store.ts, packages/revocation-list-2020/README.md, packages/revocation-list-2020/__tests__/encrypted-storage.test.js, packages/revocation-list-2020/api-extractor.json, packages/revocation-list-2020/package.json, packages/revocation-list-2020/src/entities/revocation-list-2020-data.ts, packages/revocation-list-2020/src/identifier/revocation-list-2020-store.ts, packages/revocation-list-2020/src/index.ts, packages/revocation-list-2020/src/migrations/1.createDatabase.ts, packages/revocation-list-2020/src/migrations/index.ts, packages/revocation-list-2020/src/migrations/migration-functions.ts, packages/revocation-list-2020/src/module-types/@digitalbazaar/vc/index.d.ts, packages/revocation-list-2020/src/module-types/@transmute/did-context/index.d.ts, packages/revocation-list-2020/src/module-types/express-interceptor/index.d.ts, packages/revocation-list-2020/src/module-types/jsonld-signatures/index.d.ts, packages/revocation-list-2020/src/module-types/vc-revocation-list-context/index.d.ts, packages/revocation-list-2020/src/revocation-list-2020-middleware.ts, packages/revocation-list-2020/src/revocation-list-2020-router.ts, packages/revocation-list-2020/src/revocation-list-2020-status.ts, packages/revocation-list-2020/src/revocation-list-2020.ts, packages/revocation-list-2020/src/utils.ts, packages/revocation-list-2020/tsconfig.json, pnpm-lock.yaml
Credential status plugin for the [revocation list 2020](https://w3c-ccg.github.io/vc-status-rl-2020/)
=> Feat: revocation list 2020

.github/workflows/todo.yml
=> chore: disable github action for todo

README.md, packages/cli/default/default.yml, packages/demo-explorer/.env.example
=> docs: update readme

README.md
This PR update the node and pnpm version.
https://github.com/uncefact/project-vckit/issues/143
=> docs: update instruction for node and pnpm version

README.md
=> docs: fix typo and update instruction

packages/cli/default/default.yml, packages/demo-explorer/src/components/IssueCredentialFromSchema.tsx, packages/demo-explorer/src/utils/signing.ts, packages/encrypted-storage/src/encrypted-store-middleware.ts, packages/encrypted-storage/src/migrations/1.createDatabase.ts, packages/revocation-list-2020/src/revocation-list-2020-middleware.ts
- Fix missing the additional fields from schema when issue the vc
- Fix storing the encrypted data when issue
- Fix retrieving the proofFormat when issue
=> fix: rendering issue

packages/encrypted-storage/src/migrations/index.ts
=> fix: update migration index

packages/cli/package.json
=> Updated sqlite to 5.1.1 from 5.0.8 so that apple silicon didn't need to cmpile the package

packages/demo-explorer/src/components/IssueCredentialFromSchema.tsx
=> fix: disable openattestation until metadata is configured

packages/cli/default/default.yml, packages/demo-explorer/src/components/CredentialInfo.tsx, packages/encrypted-storage/src/migrations/1.createDatabase.ts
- Fix migration script to ignore when the table is existing
- Rename active button to unrevoke
- Comment the did ethr in default config
=> fix: minor issues

packages/renderer/__tests__/renderer.test.ts, packages/renderer/fixtures/university-degree-credential.json, packages/renderer/src/renderer.ts
=> test: improve unit test in renderer package

README.md
=> docs: update README.md documentation

docker-compose.yml, packages/demo-explorer/.dockerignore, packages/demo-explorer/Dockerfile, packages/demo-explorer/README.md
=> chore: add dockerfile in demo explorer

packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml, packages/core-types/src/plugin.schema.json, packages/core-types/src/types/ITools.ts, packages/tools/README.md, packages/tools/__tests__/computeHash.test.ts, packages/tools/src/hash/multibase-encoded-256.ts
=> fix: add interface for compute hash

Dockerfile, packages/cli/default/agent.template.yml
=> chore: update DockerFile and agent template

Dockerfile
=> chore: update vckit Dockerfile

documentation/docs/manage-plugins.md
This is to create documentation of how to manage plugins in VCKit
https://github.com/gs-gs/fa-ag-trace/issues/359
=> docs: create manage plugin documentation

packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml
This PR updates the default agent configuration
https://github.com/gs-gs/fa-ag-trace/issues/475
https://github.com/gs-gs/fa-ag-trace/issues/478
=> chore: update default agent for Status plugin

documentation/README.md, documentation/package.json
[#484](https://github.com/gs-gs/fa-ag-trace/issues/484)
=> Chore: update port documentation

documentation/docs/get-started/api-server-get-started/installation.md
[488](https://github.com/gs-gs/fa-ag-trace/issues/488)
=> docs: clarify the API server installation instructions

documentation/docs/get-started/api-server-get-started/installation.md, documentation/docs/get-started/cli-get-started/installation.md, documentation/docs/get-started/demo-explorer-get-started/installation.md, documentation/docs/get-started/library-get-started/installation.md
This PR add warning for install pnpm
Resolves https://github.com/gs-gs/fa-ag-trace/issues/493
=> docs: add warning for install pnpm

documentation/README.md, documentation/package.json
Docs: https://github.com/gs-gs/fa-ag-trace/issues/498
=> docs: update document for deploy and how to run npm run serve

.github/workflows/package.yml
=> feat(cd): ghcr.io setup and docker image build workflow

documentation/docs/get-started/api-server-get-started/basic-operations.md
This PR updates the documentation regarding identifier creation.
=> docs: update identifier creation

.github/workflows/build-and-deploy-agent.yml, .github/workflows/deploy-to-s3.yml, .github/workflows/package.yml, .github/workflows/release-tagging.yml, Dockerfile, packages/demo-explorer/src/utils/signing.ts, pnpm-lock.yaml
This PR adjusts the workflows to allow manually trigger and update the dockerfile
=> chore: update workflow and dockerfile

packages/bitstringStatusList/src/entities/bitstring-status-list-entry-data.ts, packages/bitstringStatusList/src/identifier/bitstring-status-list-entry-store.ts
This PR fixes the bitstring status list data model that is facing the problem when running the vckit with postgres
=> fix: adjust bitstring status list model

packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml, packages/vc-api/README.md, packages/vc-api/package.json, packages/vc-api/src/v1-vc-api/v1-vc-router.ts, packages/vc-api/src/v2-vc-api/v2-vc-router.ts, packages/vc-api/src/vc-api-schemas/vc-api-v2.yaml, packages/vc-api/src/vc-api-schemas/vc-api.yaml, pnpm-lock.yaml
This PR adds the authentication using API key for the APIs of vc-api plugin
https://github.com/gs-gs/fa-ag-trace/issues/621
=> feat: implement authenticate for vc api

packages/bitstringStatusList/src/identifier/bitstring-status-list-entry-store.ts
This PR fixes the issue when setting status for bitstring status list credential. It was missing the set status function when integrated with the enveloping proof.
=> fix: the bitstring status is missing integration enveloping proof

packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml
=> chore: change hardcode URL to dynamic URL in agent file

.github/workflows/build-and-test.yml, documentation/docs/get-started/api-server-get-started/installation.md
This PR adds the job to build the document for the build and test workflow that will be triggered when the PR is created
Closes #232 
https://github.com/gs-gs/fa-ag-trace/issues/795
=> chore: set document build process in build and test workflow

RELEASE_MANAGEMENT_GUIDE.md
This PR adds the release management documentation 
https://github.com/gs-gs/fa-ag-trace/issues/899
=> docs: add release management guide

.github/workflows/package.yml
This PR fixes the package workflow to trigger when the release workflow run successfully
=> fix: handle trigger package workflow

.github/workflows/release.yml
=> chore: update checks write permisions on release workflow

CONTRIBUTING.md
This PR adds information regarding where the VCkit packages are published and who can publish packages.
=> docs: add packaging information

.github/workflows/build-and-test.yml, .github/workflows/build-test-publish.yml, .github/workflows/deploy-to-s3.yml, .github/workflows/package.yml, .github/workflows/release.yml
This PR updates the package manager (pnpm) and node versions within the workflow files to use the expected version.
=> ci: update package manager and node versions

packages/bitstringStatusList/README.md, packages/bitstringStatusList/package.json, packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml, packages/cli/package.json, pnpm-lock.yaml
This PR updates the Bitstring package name to comply with the NPM naming convention.
Fixes #264
=> chore: update bitstring package name

documentation/docs/vckit-plugins/revocation-list-2020.md, documentation/tutorial-example/vckit/package.json, documentation/tutorial-example/vckit/src/vckit/setup.ts, documentation/versioned_docs/version-1.0.0/vckit-plugins/revocation-list-2020.md, packages/cli/default/agent.template.yml, packages/cli/default/default-dev.yml, packages/cli/default/default.yml, packages/cli/package.json, packages/revocation-list-2020/README.md, packages/revocation-list-2020/package.json, pnpm-lock.yaml
This PR updates the Revocation List package name to follow the established naming convention. The existing Revocation List package published to NPM (`@uncefact/vckit-revocationlist`) will be deprecated in favour of the new package published (`@uncefact/vckit-revocation-list-2020`).
Fixes #265
=> chore: update revocation list package name

README.md, packages/renderer/__tests__/renderer.test.ts, packages/renderer/fixtures/univerisity-degree-credential-template-2024.json, packages/renderer/src/contexts/www.w3.org_ns_credentials_v2.json
=> feat: update doc and add render context
